functionality:
  name: python_3_10
  description: A Python 3.10 slim with anndata and mudata preinstalled.
platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages:
          - procps
      - type: python
        packages:
          - anndata~=0.8.0
          - mudata~=0.2.0
          - scanpy~=1.9.2
