functionality:
  name: r2u_22_04
  description: An R2U 22.04 with anndata and mudata preinstalled.
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: apt
        packages:
          - procps
          - libhdf5-dev
          - libgeos-dev
          - python3
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        packages:
          - anndata~=0.8.0
          - mudata~=0.2.0
          - scanpy~=1.9.2
      - type: r
        packages:
          - anndata
